jobscript=linpack.sh
coordinationscript=linpack-coordination.sh
job_id=linpack
job_type=mpijob
numnodes=$1
ppn=2
coordination='bash $AZ_BATCH_TASK_SHARED_DIR/'${coordinationscript}
hpl_MEM_GB=4
hpl_P=2
hpl_Q=$numnodes
hpl_NB=192
commandline='bash $AZ_BATCH_TASK_WORKING_DIR/'${jobscript}' '$numnodes' '$ppn' '$hpl_MEM_GB' '$hpl_P' '$hpl_Q' '$hpl_NB
jobenvsettings='[{"name":"ANALYTICS_WORKSPACE", "value":""},{"name":"ANALYTICS_KEY", "value":""}]'
input_dir=
