jobscript=linpack.sh
coordinationscript=linpack-coordination.sh
job_id=linpack
job_type=mpijob
numnodes=$1
ppn=2
np=$(bc <<< "$numnodes * $ppn")
coordination='bash $AZ_BATCH_TASK_SHARED_DIR/'${coordinationscript}
hpl_N=69120
hpl_P=2
hpl_Q=2
hpl_NB=192
commandline='sudo -E -u _azbatch bash $AZ_BATCH_TASK_WORKING_DIR/'${jobscript}' '$np' '$ppn' '$hpl_N' '$hpl_P' '$hpl_Q' '$hpl_NB
input_dir=
